document.getElementById('donation-tab').addEventListener('click',function(){
    showExceptID();
    document.getElementById('card-container').classList.remove('hidden');
    document.getElementById('donation-tab').classList.add('active');
});

document.getElementById('history-tab').addEventListener('click',function(){
    showExceptID();
    document.getElementById('history-container').classList.remove('hidden');
    document.getElementById('history-tab').classList.add('active');
});
document.getElementById('donateN').addEventListener('click',function(){
    showExceptID();
    document.getElementById('card-container').classList.remove('hidden');
    document.getElementById('donation-tab').classList.add('active');
});
document.getElementById('donateF').addEventListener('click',function(){
    showExceptID();
    document.getElementById('card-container').classList.remove('hidden');
    document.getElementById('donation-tab').classList.add('active');
});
document.getElementById('donateQ').addEventListener('click',function(){
    showExceptID();
    document.getElementById('card-container').classList.remove('hidden');
    document.getElementById('donation-tab').classList.add('active');
});

document.getElementById('blog-id').addEventListener('submit',function(event){
    event.preventDefault();
});
document.getElementById('home-id').addEventListener('submit',function(event){
    event.preventDefault();
});